name: Common setup
description: common setup for actions
runs:
  using: composite
  steps:
    - name: Tool versions
      uses: wistia/parse-tool-versions@32f568a4ffd4bfa7720ebf93f171597d1ebc979a # v2.1.1
      with:
        postfix: _TOOL_VERSION

    - name: Setup Just
      uses: extractions/setup-crate@4993624604c307fbca528d28a3c8b60fa5ecc859 # v1.4.0
      with:
        repo: casey/just
        version: ${{ env.JUST_TOOL_VERSION }}

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_TOOL_VERSION }}

    - name: Setup uv
      uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
      with:
        version: ${{ env.UV_TOOL_VERSION }}
        activate-environment: true
        enable-cache: true

    - name: Install dependencies
      shell: sh
      run: |
        just install
