name: Common setup
description: common setup for actions
runs:
  using: composite
  steps:
    - name: Tool versions
      uses: wistia/parse-tool-versions@32f568a4ffd4bfa7720ebf93f171597d1ebc979a # v2.1.1
      with:
        postfix: _TOOL_VERSION

    - name: Setup Just
      uses: extractions/setup-crate@4993624604c307fbca528d28a3c8b60fa5ecc859 # v1.4.0
      with:
        repo: casey/just
        version: ${{ env.JUST_TOOL_VERSION }}

    - name: Setup Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ env.PYTHON_TOOL_VERSION }}

    - name: Setup uv
      uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # v7.3.1
      with:
        version: ${{ env.UV_TOOL_VERSION }}
        activate-environment: true
        enable-cache: true

    - name: Install dependencies
      shell: sh
      run: |
        just install
